locals {
  tags = merge(
    {
      Environment = var.environment
      ManagedBy   = "terraform"
      Project     = var.tags["Project"]
    },
    var.tags
  )
}

# Random secrets generated by Terraform
resource "random_password" "db_password" {
  length  = 32
  special = true
}

resource "random_password" "jwt_secret" {
  length  = 64
  special = true
}

resource "random_password" "oura_api_key" {
  length  = 40
  special = false
}

# S3 bucket for Terraform state (backend can be configured after first apply)
resource "random_id" "tfstate_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "tf_state" {
  bucket = "myhealth-terraform-state-${random_id.tfstate_suffix.hex}"
}

resource "aws_s3_bucket_versioning" "tf_state" {
  bucket = aws_s3_bucket.tf_state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "tf_state" {
  bucket = aws_s3_bucket.tf_state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "tf_state" {
  bucket = aws_s3_bucket.tf_state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Networking module
module "networking" {
  source = "./modules/networking"

  cluster_name          = var.cluster_name
  vpc_cidr              = var.vpc_cidr
  tags                  = local.tags
  log_retention_in_days = var.log_retention_in_days
}

# EKS module
module "eks" {
  source = "./modules/eks"

  cluster_name           = var.cluster_name
  cluster_version        = var.cluster_version
  vpc_id                 = module.networking.vpc_id
  private_subnets        = module.networking.private_subnets
  node_security_group_id = module.networking.node_security_group_id
  node_instance_types    = var.node_instance_types
  node_min_size          = var.node_min_size
  node_max_size          = var.node_max_size
  node_desired_size      = var.node_desired_size
  tags                   = local.tags
}

# RDS module
module "rds" {
  source = "./modules/rds"

  cluster_name               = var.cluster_name
  vpc_id                     = module.networking.vpc_id
  private_subnets            = module.networking.private_subnets
  eks_node_security_group_id = module.networking.node_security_group_id
  instance_class             = var.rds_instance_class
  db_username                = "myhealth_user"
  db_password                = random_password.db_password.result
  multi_az                   = false
  backup_retention_days      = 7
  skip_final_snapshot        = true
  tags                       = local.tags
}

# ECR module
module "ecr" {
  source = "./modules/ecr"
  tags   = local.tags
}

# Secrets Manager module
module "secrets_manager" {
  source = "./modules/secrets-manager"

  oura_api_key   = random_password.oura_api_key.result
  db_username    = "myhealth_user"
  db_password    = random_password.db_password.result
  db_host        = module.rds.db_address
  jwt_secret_key = random_password.jwt_secret.result
  tags           = local.tags
}

# API Gateway module (optional until ACM cert + backend provided)
module "api_gateway" {
  count = var.acm_certificate_arn != "" && var.backend_url != "" ? 1 : 0

  source              = "./modules/api-gateway"
  backend_url         = var.backend_url
  acm_certificate_arn = var.acm_certificate_arn
  tags                = local.tags
}
