# Outputs for EKS Three-Tier Application

# Cluster outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_name
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_version" {
  description = "EKS cluster version"
  value       = module.eks.cluster_version
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN associated with EKS cluster"
  value       = module.eks.cluster_iam_role_arn
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
}

output "cluster_primary_security_group_id" {
  description = "The cluster primary security group ID created by EKS"
  value       = module.eks.cluster_primary_security_group_id
}

# OIDC outputs
output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = module.eks.cluster_oidc_issuer_url
}

output "oidc_provider_arn" {
  description = "The ARN of the OIDC Provider if enabled"
  value       = module.eks.oidc_provider_arn
}

# Node group outputs
output "eks_managed_node_groups" {
  description = "Map of attribute maps for all EKS managed node groups created"
  value       = module.eks.eks_managed_node_groups
  sensitive   = true
}

output "node_security_group_id" {
  description = "ID of the node shared security group"
  value       = module.eks.node_security_group_id
}

# VPC outputs
output "vpc_id" {
  description = "ID of the VPC where the cluster and workers are deployed"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "The CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "database_subnets" {
  description = "List of IDs of database subnets"
  value       = module.vpc.database_subnets
}

output "nat_gateway_ips" {
  description = "List of public Elastic IPs created for AWS NAT Gateway"
  value       = module.vpc.nat_public_ips
}

# kubectl config
output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/templates/kubeconfig.tpl", {
    cluster_name               = module.eks.cluster_name
    endpoint                   = module.eks.cluster_endpoint
    region                     = var.region
    certificate_authority_data = module.eks.cluster_certificate_authority_data
  })
  sensitive = true
}

# Connection commands
output "cluster_connect_command" {
  description = "Command to connect to the EKS cluster"
  value       = "aws eks update-kubeconfig --region ${var.region} --name ${module.eks.cluster_name}"
}

# Security outputs
output "cluster_encryption_config" {
  description = "Cluster encryption configuration"
  value = var.enable_cluster_encryption ? [{
    provider_key_arn = aws_kms_key.eks[0].arn
    resources        = ["secrets"]
  }] : []
}

# Load Balancer Controller IAM role
output "aws_load_balancer_controller_role_arn" {
  description = "The Amazon Resource Name (ARN) specifying the IAM role for AWS Load Balancer Controller"
  value       = module.load_balancer_controller_irsa_role.iam_role_arn
}

# External Secrets Operator IAM role
output "external_secrets_operator_role_arn" {
  description = "The Amazon Resource Name (ARN) specifying the IAM role for External Secrets Operator"
  value       = module.external_secrets_irsa_role.iam_role_arn
}

# Cluster Autoscaler IAM role
output "cluster_autoscaler_role_arn" {
  description = "The Amazon Resource Name (ARN) specifying the IAM role for Cluster Autoscaler"
  value       = module.cluster_autoscaler_irsa_role.iam_role_arn
}

# EBS CSI Driver IAM role
output "ebs_csi_driver_role_arn" {
  description = "The Amazon Resource Name (ARN) specifying the IAM role for EBS CSI Driver"
  value       = module.ebs_csi_irsa_role.iam_role_arn
}

# Monitoring outputs
output "monitoring_namespace" {
  description = "Kubernetes namespace for monitoring stack"
  value       = "monitoring"
}

output "grafana_admin_password" {
  description = "Grafana admin password"
  value       = var.monitoring_config.grafana.admin_password
  sensitive   = true
}

# Application namespaces
output "application_namespaces" {
  description = "List of application namespaces created"
  value       = ["frontend", "backend", "database"]
}

# Storage class
output "default_storage_class" {
  description = "Default storage class for the cluster"
  value       = "gp3"
}

# Ingress information
output "ingress_class" {
  description = "Ingress class for ALB"
  value       = "alb"
}

# Region and availability zones
output "region" {
  description = "AWS region"
  value       = var.region
}

output "availability_zones" {
  description = "List of availability zones used"
  value       = local.azs
}

# Tags
output "common_tags" {
  description = "Common tags applied to resources"
  value       = var.tags
}

# Cost estimation helper
output "resource_summary" {
  description = "Summary of key resources for cost estimation"
  value = {
    cluster_name    = module.eks.cluster_name
    node_groups     = length(var.node_groups)
    total_min_nodes = sum([for ng in var.node_groups : ng.min_size])
    total_max_nodes = sum([for ng in var.node_groups : ng.max_size])
    nat_gateways    = length(local.azs)
    load_balancers  = 1 # ALB for ingress
    storage_classes = 1 # gp3
  }
}
