# External Secrets Operator for AWS Secrets Manager
# This configuration enables secure secret management for EKS

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKey:
            name: awssm-secret
            key: access-key
          secretKey:
            name: awssm-secret
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: backend
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_DB: "{{ .postgres_db }}"
        DATABASE_URL: "postgresql://{{ .postgres_user }}:{{ .postgres_password }}@postgresql.database.svc.cluster.local:5432/{{ .postgres_db }}"
  data:
  - secretKey: postgres_user
    remoteRef:
      key: three-tier-app/database
      property: username
  - secretKey: postgres_password
    remoteRef:
      key: three-tier-app/database
      property: password
  - secretKey: postgres_db
    remoteRef:
      key: three-tier-app/database
      property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: backend
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        JWT_SECRET: "{{ .jwt_secret }}"
        API_KEY: "{{ .api_key }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: three-tier-app/api
      property: jwt_secret
  - secretKey: api_key
    remoteRef:
      key: three-tier-app/api
      property: api_key
  - secretKey: redis_password
    remoteRef:
      key: three-tier-app/api
      property: redis_password
---
# IRSA Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/three-tier-external-secrets-role
---
# ClusterSecretStore for cluster-wide secret management
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets-system
---
# Monitoring credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secrets-manager
    kind: ClusterSecretStore
  target:
    name: monitoring-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        grafana-admin-user: "{{ .grafana_user }}"
        grafana-admin-password: "{{ .grafana_password }}"
        alertmanager-webhook-url: "{{ .webhook_url }}"
  data:
  - secretKey: grafana_user
    remoteRef:
      key: three-tier-app/monitoring
      property: grafana_admin_user
  - secretKey: grafana_password
    remoteRef:
      key: three-tier-app/monitoring
      property: grafana_admin_password
  - secretKey: webhook_url
    remoteRef:
      key: three-tier-app/monitoring
      property: alertmanager_webhook_url
