# Pod Security Standards Configuration
# Implements security policies across all namespaces

# Frontend namespace - baseline security
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Backend namespace - restricted security
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Database namespace - restricted security
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Monitoring namespace - baseline security (for compatibility with monitoring tools)
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: restricted
---
# Security Policy for Frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-security-policy
  namespace: frontend
spec:
  podSelector:
    matchLabels:
      app: frontend-web
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: backend
    ports:
    - protocol: TCP
      port: 3000
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
# Security Policy for Backend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-security-policy
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: backend-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: frontend
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 5432
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
---
# Security Policy for Database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-security-policy
  namespace: database
spec:
  podSelector:
    matchLabels:
      app: postgresql
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: backend
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
# SecurityContext for Frontend Pods
apiVersion: v1
kind: Pod
metadata:
  name: frontend-security-template
  namespace: frontend
  annotations:
    description: "Security template for frontend pods"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: frontend
    image: nginx:1.25-alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    - name: var-cache-volume
      mountPath: /var/cache/nginx
    - name: var-run-volume
      mountPath: /var/run
  volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: var-cache-volume
    emptyDir: {}
  - name: var-run-volume
    emptyDir: {}
---
# SecurityContext for Backend Pods
apiVersion: v1
kind: Pod
metadata:
  name: backend-security-template
  namespace: backend
  annotations:
    description: "Security template for backend pods"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: backend
    image: node:18-alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    - name: app-logs
      mountPath: /app/logs
  volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: app-logs
    emptyDir: {}
---
# SecurityContext for Database Pods
apiVersion: v1
kind: Pod
metadata:
  name: database-security-template
  namespace: database
  annotations:
    description: "Security template for database pods"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: postgresql
    image: postgres:15-alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false  # PostgreSQL needs to write to data directory
      runAsNonRoot: true
      runAsUser: 999
      runAsGroup: 999
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    - name: tmp-volume
      mountPath: /tmp
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: tmp-volume
    emptyDir: {}
---
# AdmissionController Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-policies
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: security-baseline
    spec:
      validationFailureAction: enforce
      background: true
      rules:
      - name: check-security-context
        match:
          any:
          - resources:
              kinds:
              - Pod
        validate:
          message: "Security context is required"
          pattern:
            spec:
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              containers:
              - name: "*"
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
      - name: require-resource-limits
        match:
          any:
          - resources:
              kinds:
              - Pod
        validate:
          message: "Resource limits are required"
          pattern:
            spec:
              containers:
              - name: "*"
                resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
                  requests:
                    memory: "?*"
                    cpu: "?*"
      - name: block-privileged-containers
        match:
          any:
          - resources:
              kinds:
              - Pod
        validate:
          message: "Privileged containers are not allowed"
          pattern:
            spec:
              =(securityContext):
                =(privileged): "false"
              containers:
              - name: "*"
                =(securityContext):
                  =(privileged): "false"
