# External Secrets Operator for Azure Key Vault
# This configuration enables secure secret management for AKS

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: backend
spec:
  provider:
    azurekv:
      vaultUrl: "https://three-tier-app-kv.vault.azure.net/"
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
      tenantId: "TENANT_ID"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: backend
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_USER: "{{ .postgres_user }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_DB: "{{ .postgres_db }}"
        DATABASE_URL: "postgresql://{{ .postgres_user }}:{{ .postgres_password }}@postgresql.database.svc.cluster.local:5432/{{ .postgres_db }}"
  data:
  - secretKey: postgres_user
    remoteRef:
      key: postgres-user
  - secretKey: postgres_password
    remoteRef:
      key: postgres-password
  - secretKey: postgres_db
    remoteRef:
      key: postgres-database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: backend
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore
  target:
    name: api-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        JWT_SECRET: "{{ .jwt_secret }}"
        API_KEY: "{{ .api_key }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: jwt-secret
  - secretKey: api_key
    remoteRef:
      key: api-key
  - secretKey: redis_password
    remoteRef:
      key: redis-password
---
# ClusterSecretStore for cluster-wide secret management
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-keyvault
spec:
  provider:
    azurekv:
      vaultUrl: "https://three-tier-app-kv.vault.azure.net/"
      authType: ManagedIdentity
      authSecretRef:
        clientId:
          name: azure-wi-secret
          key: ClientID
---
# Monitoring credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-cluster-keyvault
    kind: ClusterSecretStore
  target:
    name: monitoring-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        grafana-admin-user: "{{ .grafana_user }}"
        grafana-admin-password: "{{ .grafana_password }}"
        alertmanager-webhook-url: "{{ .webhook_url }}"
  data:
  - secretKey: grafana_user
    remoteRef:
      key: grafana-admin-user
  - secretKey: grafana_password
    remoteRef:
      key: grafana-admin-password
  - secretKey: webhook_url
    remoteRef:
      key: alertmanager-webhook-url
---
# Azure Workload Identity Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: external-secrets-system
  annotations:
    azure.workload.identity/client-id: "CLIENT_ID"
    azure.workload.identity/tenant-id: "TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
---
# SecretProviderClass for CSI driver integration
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-csi
  namespace: backend
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "CLIENT_ID"
    keyvaultName: "three-tier-app-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: api-key
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: keyvault-secrets
    type: Opaque
    data:
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: api-key
      key: API_KEY
